// frontend/src/pages/GroupsPage.tsx
import { useState, useEffect, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { getMyGroups, leaveGroup, deleteGroup } from '../lib/groupsService.js';
import GroupsList from '../designsystem/components/GroupsList';
import type { GroupData } from '../designsystem/components/GroupCard/GroupCard';
import Button from '../designsystem/components/Button';

// Ported from GroupsPage.svelte (commit d6b2566^). Lists the signed-in user's
// groups via getMyGroups. Navigation lives in Layout, so this page never renders
// the nav itself and owns the single page <h1>. The four data states (loading,
// error, empty, populated) are handled here; GroupsList is rendered only once
// there are groups to show.

export default function GroupsPage() {
  const navigate = useNavigate();

  const [groups, setGroups] = useState<GroupData[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Bumping refreshKey re-runs the load effect. reload() is a stable callback so
  // it can be handed to Retry / onRefresh without re-creating on every render.
  const [refreshKey, setRefreshKey] = useState(0);
  const reload = useCallback(() => setRefreshKey((k) => k + 1), []);

  useEffect(() => {
    let cancelled = false;

    async function fetchGroups() {
      setLoading(true);
      setError(null);
      try {
        const data = await getMyGroups();
        if (!cancelled) setGroups(data);
      } catch (err) {
        if (!cancelled) {
          setError(err instanceof Error ? err.message : 'Failed to load groups');
          setGroups([]);
        }
      } finally {
        if (!cancelled) setLoading(false);
      }
    }

    fetchGroups();
    return () => {
      cancelled = true;
    };
  }, [refreshKey]);

  async function handleLeaveGroup(group: GroupData) {
    try {
      await leaveGroup(group.identifier);
      reload();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to leave group');
    }
  }

  async function handleDeleteGroup(group: GroupData) {
    if (!group.isOwner) return;
    try {
      await deleteGroup(group.identifier);
      reload();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to delete group');
    }
  }

  return (
    <div className="min-h-screen bg-neutral-0 dark:bg-secondary-900">
      <div className="max-w-6xl mx-auto px-lg py-lg space-y-lg">
        <header className="space-y-sm">
          <h1 className="text-3xl font-heading font-bold text-[var(--color-text-primary)]">
            My Groups
          </h1>
          <p className="text-[var(--color-text-secondary)]">
            Manage your confidence picks groups and track your performance.
          </p>
        </header>

        {loading ? (
          /* Loading state */
          <div className="flex justify-center items-center py-12">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary-600" />
            <span className="ml-3 text-[var(--color-text-secondary)]">Loading groups...</span>
          </div>
        ) : error ? (
          /* Error state */
          <div className="p-md bg-error-50 dark:bg-error-900/20 border border-error-200 dark:border-error-800 rounded-base">
            <div className="flex items-center">
              <svg
                className="w-5 h-5 text-error-500 mr-sm"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
                aria-hidden="true"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                />
              </svg>
              <div>
                <h3 className="font-semibold text-error-700 dark:text-error-400">
                  Error Loading Groups
                </h3>
                <p className="text-error-600 dark:text-error-300">{error}</p>
              </div>
            </div>
            <div className="mt-sm">
              <Button variant="secondary" size="sm" onClick={reload}>
                Retry
              </Button>
            </div>
          </div>
        ) : groups.length === 0 ? (
          /* Empty state */
          <div className="text-center py-12 space-y-md">
            <p className="text-[var(--color-text-secondary)]">
              No groups yet — Create or Join one
            </p>
            <div className="flex flex-col sm:flex-row gap-sm justify-center">
              <Button variant="primary" onClick={() => navigate('/create-group')}>
                Create Group
              </Button>
              <Button variant="secondary" onClick={() => navigate('/join-group')}>
                Join Group
              </Button>
            </div>
          </div>
        ) : (
          /* Populated state */
          <GroupsList
            groups={groups}
            showHeader={false}
            onCreateNew={() => navigate('/create-group')}
            onJoinExisting={() => navigate('/join-group')}
            onViewGroup={() => navigate('/group-details')}
            onEditGroup={(group) => navigate(`/edit-group/${group.identifier}`)}
            onLeaveGroup={handleLeaveGroup}
            onDeleteGroup={handleDeleteGroup}
            onRefresh={reload}
          />
        )}
      </div>
    </div>
  );
}

// frontend/src/components/GroupsPage.svelte
<script>
  import { onMount } from 'svelte';
  import { navigateTo } from '../lib/router.js';
  import GroupsList from '../designsystem/components/GroupsList.svelte';
  import AuthService from '../lib/authService.js';
  import { getMyGroups, leaveGroup, deleteGroup } from '../lib/groupsService.js';
  import ConfirmDeleteModal from './ConfirmDeleteModal.svelte';

  let groups = [];
  let isLoading = false;
  let error = null;
  let deleting = false;
  let showDeleteModal = false;
  let groupPendingDelete = null;

  onMount(async () => {
    await loadGroups();
  });

  async function loadGroups() {
    isLoading = true;
    error = null;
    try {
      groups = await getMyGroups();
    } catch (err) {
      error = err.message;
      console.error('Error loading groups:', err);
      groups = [];
    } finally {
      isLoading = false;
    }
  }

  function handleCreateNew() {
    navigateTo('/groups/create');
  }

  function handleJoinExisting() {
    navigateTo('/groups/join');
  }

  function handleViewGroup(group) {
    // Use identifier for route (backend identifies groups by identifier)
    if (!group || !group.identifier) return;
    navigateTo(`/groups/${group.identifier}`);
  }

  function handleEditGroup(group) {
    if (!group || !group.identifier) return;
    navigateTo(`/groups/${group.identifier}/edit`);
  }

  async function handleLeaveGroup(group) {
    if (!group) return;
    if (confirm(`Are you sure you want to leave "${group.name}"?`)) {
      try {
        await leaveGroup(group.identifier);
        groups = groups.filter(g => g.identifier !== group.identifier);
      } catch (err) {
        error = err.message;
        console.error('Error leaving group:', err);
      }
    }
  }

  function handleDeleteGroup(group) {
    if (!group?.isOwner) return; // Only allow owner
    groupPendingDelete = group;
    showDeleteModal = true;
    error = null;
  }

  async function confirmDelete() {
    if (!groupPendingDelete) return;
    deleting = true;
    error = null;
    try {
      await deleteGroup(groupPendingDelete.identifier);
      groups = groups.filter(g => g.identifier !== groupPendingDelete.identifier);
      showDeleteModal = false;
      groupPendingDelete = null;
    } catch (e) {
      error = e.message;
    } finally {
      deleting = false;
    }
  }
</script>

<div class="min-h-screen bg-neutral-0 dark:bg-secondary-900 pt-16">
  <div class="max-w-6xl mx-auto px-md py-lg">
    <!-- Page Header -->
    <div class="mb-lg">
      <h1 class="text-3xl font-heading font-bold text-[var(--color-text-primary)] mb-sm">
        My Groups
      </h1>
      <p class="text-[var(--color-text-secondary)]">
        Manage your confidence picks groups and track your performance.
      </p>
    </div>

    <!-- Error Message -->
    {#if error}
      <div class="mb-lg p-md bg-error-50 dark:bg-error-900/20 border border-error-200 dark:border-error-800 rounded-base">
        <div class="flex items-center">
          <svg class="w-5 h-5 text-error-500 mr-sm" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
          </svg>
          <div>
            <h3 class="font-semibold text-error-700 dark:text-error-400">Error Loading Groups</h3>
            <p class="text-error-600 dark:text-error-300">{error}</p>
          </div>
        </div>
        <button
          class="mt-sm px-sm py-xs bg-error-100 dark:bg-error-800 text-error-700 dark:text-error-300 rounded hover:bg-error-200 dark:hover:bg-error-700 transition-colors"
          on:click={loadGroups}
        >
          Try Again
        </button>
      </div>
    {/if}

    <!-- Groups List -->
    <GroupsList 
      {groups}
      {isLoading}
  showHeader={false}
      onCreateNew={handleCreateNew}
      onJoinExisting={handleJoinExisting}
      onViewGroup={handleViewGroup}
      onEditGroup={handleEditGroup}
      onLeaveGroup={handleLeaveGroup}
  onDeleteGroup={handleDeleteGroup}
    />

  <!-- Stats section removed per UX request -->
  </div>
</div>

<ConfirmDeleteModal
  open={showDeleteModal}
  name={groupPendingDelete?.name}
  slug={groupPendingDelete?.identifier}
  loading={deleting}
  error={error && deleting ? error : null}
  on:cancel={() => { if (!deleting) { showDeleteModal = false; groupPendingDelete = null; } }}
  on:confirm={confirmDelete}
/>
