// frontend/src/pages/ProfilePage.tsx
import { useState } from 'react';
import { useAuth } from '../contexts/AuthContext';
import AuthService from '../lib/authService.js';
import Avatar from '../designsystem/components/Avatar';
import Button from '../designsystem/components/Button';
import TextField from '../designsystem/components/TextField';
import InlineToast from '../designsystem/components/InlineToast';
import type { ToastVariant } from '../designsystem/components/InlineToast';

interface ToastState {
  open: boolean;
  message: string;
  variant: ToastVariant;
}

function capitalize(value: string): string {
  if (!value) return '';
  return value.charAt(0).toUpperCase() + value.slice(1);
}

export default function ProfilePage() {
  const { user, setAuthUser } = useAuth();

  const [editingName, setEditingName] = useState(false);
  const [newName, setNewName] = useState('');
  const [savingName, setSavingName] = useState(false);
  const [toast, setToast] = useState<ToastState>({
    open: false,
    message: '',
    variant: 'error',
  });

  if (!user) {
    return (
      <div className="max-w-3xl mx-auto px-sm py-xl sm:px-lg text-center text-[var(--color-text-secondary)]">
        No user data.
      </div>
    );
  }

  function startEditingName() {
    setNewName(user!.name || '');
    setEditingName(true);
  }

  function cancelEditingName() {
    setNewName('');
    setEditingName(false);
  }

  async function saveNewName() {
    const trimmed = newName.trim();
    if (!trimmed || trimmed === user!.name) {
      cancelEditingName();
      return;
    }

    setSavingName(true);
    try {
      const updatedUser = await AuthService.updateUserName(trimmed);
      // updateUserName may omit provider; keep the existing one so the context
      // User (provider required) stays well-formed.
      setAuthUser({ ...updatedUser, provider: updatedUser.provider ?? user!.provider });
      setEditingName(false);
      setNewName('');
    } catch (err) {
      setToast({
        open: true,
        message: err instanceof Error ? err.message : 'Failed to update name',
        variant: 'error',
      });
    } finally {
      setSavingName(false);
    }
  }

  return (
    <div className="max-w-4xl mx-auto px-sm py-lg sm:px-lg space-y-xl">
      <header className="flex flex-col sm:flex-row items-center sm:items-end gap-md">
        <Avatar
          name={user.name}
          email={user.email}
          pictureUrl={user.pictureUrl}
          variant="lg"
          className="w-16 h-16 md:w-20 md:h-20 border-4 border-primary-100 dark:border-primary-800 shadow-md flex-shrink-0"
        />
        <div className="text-center sm:text-left space-y-sm">
          <h1 className="text-3xl font-heading font-bold text-[var(--color-text-primary)]">
            My Profile
          </h1>
          <p className="text-[var(--color-text-secondary)]">
            Manage your account details and preferences.
          </p>
        </div>
      </header>

      <section className="p-lg rounded-base border border-secondary-200 dark:border-secondary-700 bg-neutral-0 dark:bg-secondary-800 space-y-md">
        <h2 className="text-xl font-heading font-semibold text-[var(--color-text-primary)]">
          Account Details
        </h2>
        <div className="space-y-sm text-sm">
          {/* Name (editable) */}
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-xs">
            <span className="text-[var(--color-text-secondary)]">Name</span>
            {editingName ? (
              <div className="flex flex-col gap-xs sm:flex-row sm:items-center">
                <div className="min-w-0 flex-1">
                  <TextField
                    value={newName}
                    onChange={setNewName}
                    placeholder="Enter your name"
                    size="sm"
                    disabled={savingName}
                  />
                </div>
                <div className="flex gap-xs">
                  <div className="relative inline-toast-anchor">
                    <Button
                      variant="primary"
                      size="sm"
                      onClick={saveNewName}
                      disabled={savingName}
                      loading={savingName}
                    >
                      {savingName ? 'Saving...' : 'Save'}
                    </Button>
                    <InlineToast
                      open={toast.open}
                      message={toast.message}
                      variant={toast.variant}
                      onClose={() => setToast((t) => ({ ...t, open: false }))}
                    />
                  </div>
                  <Button
                    variant="secondary"
                    size="sm"
                    onClick={cancelEditingName}
                    disabled={savingName}
                  >
                    Cancel
                  </Button>
                </div>
              </div>
            ) : (
              <div className="flex items-center gap-xs">
                <span className="font-medium text-[var(--color-text-primary)]">
                  {user.name || '—'}
                </span>
                <Button variant="tertiary" size="sm" onClick={startEditingName}>
                  Edit
                </Button>
              </div>
            )}
          </div>

          {/* Email (read-only) */}
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-xs">
            <span className="text-[var(--color-text-secondary)]">Email</span>
            <span className="font-medium text-[var(--color-text-primary)] break-all">
              {user.email}
            </span>
          </div>

          {/* Provider (read-only) */}
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-xs">
            <span className="text-[var(--color-text-secondary)]">Provider</span>
            <span className="font-medium text-[var(--color-text-primary)]">
              {capitalize(user.provider || 'google')}
            </span>
          </div>
        </div>
      </section>

      <section className="flex justify-start">
        <Button variant="destructive" onClick={() => AuthService.logout()}>
          Logout
        </Button>
      </section>
    </div>
  );
}

// frontend/src/components/ProfilePage.svelte
<script>
	import { onMount } from 'svelte';
	import AuthService from '../lib/authService.js';
	import { auth, setAuthUser } from '../lib/authStore.js';
	import { navigateTo } from '../lib/router.js';
	import TextField from '../designsystem/components/TextField.svelte';

	let loading = true;
	let error = null;
	let user = null;
			let pictureFailed = false;
			let imgSources = [];
			let currentSrcIndex = 0;

	// Name editing state
	let editingName = false;
	let newName = '';
	let savingName = false;
	let nameError = '';

	// Derive from store reactively
	$: storeUser = $auth.user;

	function initials(name) {
		if (!name) return '?';
		return name.split(/\s+/).slice(0,2).map(p=>p[0]?.toUpperCase()).join('');
	}

	function startEditingName() {
		editingName = true;
		newName = user.name || '';
		nameError = '';
	}

	function cancelEditingName() {
		editingName = false;
		newName = '';
		nameError = '';
	}

	async function saveNewName() {
		if (!newName || newName.trim().length === 0) {
			nameError = 'Name cannot be empty';
			return;
		}

		if (newName.trim() === user.name) {
			cancelEditingName();
			return;
		}

		savingName = true;
		nameError = '';

		try {
			const updatedUser = await AuthService.updateUserName(newName.trim());
			user = updatedUser;
			setAuthUser(updatedUser);
			editingName = false;
			newName = '';
		} catch (err) {
			nameError = err.message || 'Failed to update name';
		} finally {
			savingName = false;
		}
	}

	async function loadUser() {
		loading = true;
		error = null;
		try {
			// Try existing enriched user first
			user = AuthService.getUser();
			if (!user || !user.pictureUrl) {
				const fresh = await AuthService.getCurrentUser();
				if (fresh) {
					user = fresh;
					setAuthUser(fresh); // update global store to include pictureUrl
				}
			}
				if (user?.pictureUrl) {
					// Generate candidate image URLs (Google profile variants)
					const base = user.pictureUrl;
					const variants = new Set();
					variants.add(base);
					if (/=s\d+-c$/.test(base)) {
						variants.add(base.replace(/=s\d+-c$/, '=s128-c'));
						variants.add(base.replace(/=s\d+-c$/, '=s256-c'));
						variants.add(base.replace(/=s\d+-c$/, '')); // no size param
					} else if (!/[?&]sz=/.test(base)) {
						variants.add(base + (base.includes('?') ? '&' : '?') + 'sz=256');
					}
					imgSources = Array.from(variants);
					currentSrcIndex = 0;
				} else {
					imgSources = [];
				}
			if (!user) {
				navigateTo('/login');
			}
		} catch (e) {
			console.error(e);
			error = 'Unable to load profile';
		} finally {
			loading = false;
		}
	}

	onMount(loadUser);
</script>

{#if loading}
	<div class="max-w-3xl mx-auto px-lg py-xl text-center text-[var(--color-text-secondary)]">Loading profile...</div>
{:else if error}
	<div class="max-w-3xl mx-auto px-lg py-xl">
		<div class="p-md rounded-base border border-error-300 dark:border-error-700 bg-error-50 dark:bg-error-900/30 text-error-700 dark:text-error-300">
			{error}
		</div>
	</div>
{:else if user}
	<div class="max-w-4xl mx-auto px-lg py-lg space-y-xl">
		<header class="flex flex-col sm:flex-row items-center sm:items-end gap-md">
			<!-- Avatar -->
									{#if user.pictureUrl && !pictureFailed}
										<img
											src={imgSources[currentSrcIndex] || user.pictureUrl}
											alt={user.name}
												class="w-16 h-16 md:w-20 md:h-20 rounded-full object-cover border-4 border-primary-100 dark:border-primary-800 shadow-md flex-shrink-0"
											referrerpolicy="no-referrer"
											crossorigin="anonymous"
											on:error={() => {
												if (currentSrcIndex < imgSources.length - 1) {
													currentSrcIndex += 1;
													console.warn('Avatar load failed, trying next variant', imgSources[currentSrcIndex]);
												} else {
													pictureFailed = true;
													console.error('All avatar variants failed to load. Falling back to initials.', imgSources);
												}
											}}
										/>
							{:else}
								<div class="w-16 h-16 md:w-20 md:h-20 rounded-full bg-primary-500 flex items-center justify-center text-neutral-0 text-2xl font-heading font-semibold shadow-md flex-shrink-0">
					{initials(user.name || user.email)}
				</div>
			{/if}
			<div class="text-center sm:text-left space-y-sm">
				<h1 class="text-3xl font-heading font-bold text-[var(--color-text-primary)]">My Profile</h1>
				<p class="text-[var(--color-text-secondary)]">Manage your account details and preferences.</p>
			</div>
		</header>

		<section class="grid grid-cols-1 md:grid-cols-3 gap-lg">
			<div class="md:col-span-2 space-y-lg">
				<!-- Basic Info Card -->
				<div class="p-lg rounded-base border border-secondary-200 dark:border-secondary-700 bg-neutral-0 dark:bg-secondary-800 space-y-md">
					<h2 class="text-xl font-heading font-semibold text-[var(--color-text-primary)]">Account Details</h2>
					<div class="space-y-sm text-sm">
						<div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-xs">
							<span class="text-[var(--color-text-secondary)]">Name</span>
							{#if editingName}
								<div class="flex flex-col gap-xs sm:flex-row sm:items-center">
									<div class="min-w-0 flex-1">
										<TextField
											bind:value={newName}
											placeholder="Enter your name"
											size="sm"
											validationState={nameError ? 'error' : 'none'}
											validationMessage={nameError}
											disabled={savingName}
										/>
									</div>
									<div class="flex gap-xs">
										<button
											class="px-xs py-xxxs bg-primary-500 text-neutral-0 rounded text-xs font-medium hover:bg-primary-600 transition-colors duration-fast disabled:opacity-50"
											on:click={saveNewName}
											disabled={savingName}
										>
											{savingName ? 'Saving...' : 'Save'}
										</button>
										<button
											class="px-xs py-xxxs bg-secondary-100 text-secondary-900 border border-secondary-300 rounded text-xs font-medium hover:bg-secondary-200 transition-colors duration-fast dark:bg-secondary-700 dark:text-secondary-50 dark:border-secondary-500 dark:hover:bg-secondary-600"
											on:click={cancelEditingName}
											disabled={savingName}
										>
											Cancel
										</button>
									</div>
								</div>
							{:else}
								<div class="flex items-center gap-xs">
									<span class="font-medium text-[var(--color-text-primary)]">{user.name || '—'}</span>
									<button
										class="text-primary-500 hover:text-primary-600 transition-colors duration-fast"
										on:click={startEditingName}
										title="Edit name"
									>
										<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
											<path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"></path>
										</svg>
									</button>
								</div>
							{/if}
						</div>
						<div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-xs">
							<span class="text-[var(--color-text-secondary)]">Email</span>
							<span class="font-medium text-[var(--color-text-primary)] break-all">{user.email}</span>
						</div>
						<div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-xs">
							<span class="text-[var(--color-text-secondary)]">Provider</span>
							<span class="font-medium capitalize text-[var(--color-text-primary)]">{user.provider || 'google'}</span>
						</div>
					</div>
				</div>
			</div>
			<!-- Quick Actions / Secondary -->
			<div class="space-y-lg">
				<div class="p-lg rounded-base border border-secondary-200 dark:border-secondary-700 bg-neutral-0 dark:bg-secondary-800 space-y-md">
					<h2 class="text-lg font-heading font-semibold text-[var(--color-text-primary)]">Quick Actions</h2>
					<div class="flex flex-col gap-sm">
						<button class="px-md py-xs bg-primary-500 text-neutral-0 rounded-base text-sm font-medium hover:bg-primary-600 transition-colors duration-fast" on:click={() => navigateTo('/groups')}>
							View Your Groups
						</button>
						<button class="px-md py-xs bg-secondary-100 text-secondary-900 border border-secondary-300 rounded-base text-sm font-medium hover:bg-secondary-200 transition-colors duration-fast dark:bg-secondary-700 dark:text-secondary-50 dark:border-secondary-500 dark:hover:bg-secondary-600" on:click={() => navigateTo('/groups/create')}>
							Create New Group
						</button>
						<button class="px-md py-xs bg-secondary-100 text-secondary-900 border border-secondary-300 rounded-base text-sm font-medium hover:bg-secondary-200 transition-colors duration-fast dark:bg-secondary-700 dark:text-secondary-50 dark:border-secondary-500 dark:hover:bg-secondary-600" on:click={() => navigateTo('/groups/join')}>
							Join Group
						</button>
					</div>
				</div>
			</div>
		</section>
	</div>
{:else}
	<div class="max-w-3xl mx-auto px-lg py-xl text-center text-[var(--color-text-secondary)]">No user data.</div>
{/if}

<style>
	/* Minimal component-specific styles if needed */
</style>
