// frontend/src/components/CreateGroupForm.svelte
<script>
  import Button from '../designsystem/components/Button.svelte';
  import TextField from '../designsystem/components/TextField.svelte';
  
  export let onSubmit = () => {};
  export let onCancel = () => {};
  export let isLoading = false;
  
  let formData = {
    name: '',
    identifier: '',
    description: ''
  };
  
  let errors = {};
  
  function validateForm() {
    errors = {};
    
    if (!formData.name.trim()) {
      errors.name = 'Group name is required';
    } else if (formData.name.length < 3) {
      errors.name = 'Group name must be at least 3 characters';
    } else if (formData.name.length > 50) {
      errors.name = 'Group name must be 50 characters or less';
    }
    
    if (!formData.identifier.trim()) {
      errors.identifier = 'Group ID is required';
    } else if (!/^[a-zA-Z0-9-_]+$/.test(formData.identifier)) {
      errors.identifier = 'Group ID can only contain letters, numbers, hyphens, and underscores';
    } else if (formData.identifier.length < 3) {
      errors.identifier = 'Group ID must be at least 3 characters';
    } else if (formData.identifier.length > 30) {
      errors.identifier = 'Group ID must be 30 characters or less';
    }
    
    if (formData.description && formData.description.length > 200) {
      errors.description = 'Description must be 200 characters or less';
    }
    
    return Object.keys(errors).length === 0;
  }
  
  function handleSubmit() {
    if (validateForm()) {
      onSubmit(formData);
    }
  }
  
  function generateIdentifier() {
    // Generate a clean identifier from the name
    const cleanName = formData.name
      .toLowerCase()
      .replace(/[^a-zA-Z0-9\s]/g, '')
      .replace(/\s+/g, '-')
      .substring(0, 30);
    
    formData.identifier = cleanName;
  }
  
  // Auto-generate identifier when name changes
  $: if (formData.name && !formData.identifier) {
    generateIdentifier();
  }
</script>

<div class="bg-white border border-gray-200 rounded-lg p-6">
  <h2 class="text-xl font-semibold text-gray-900 mb-6">Create New Group</h2>
  
  <form on:submit|preventDefault={handleSubmit} class="space-y-4">
    <TextField
      label="Group Name"
      bind:value={formData.name}
      placeholder="Enter group name"
      validationMessage={errors.name}
      validationState={errors.name ? 'error' : 'none'}
      required
      disabled={isLoading}
    />
    
    <div>
      <TextField
        label="Group ID"
        bind:value={formData.identifier}
        placeholder="unique-group-id"
        validationMessage={errors.identifier}
        validationState={errors.identifier ? 'error' : 'none'}
        required
        disabled={isLoading}
      />
      <p class="mt-1 text-sm text-gray-500">
        This will be used to share your group with others. It must be unique.
      </p>
    </div>
    
    <TextField
      label="Description (Optional)"
      bind:value={formData.description}
      placeholder="Describe your group..."
      validationMessage={errors.description}
      validationState={errors.description ? 'error' : 'none'}
      multiline
      disabled={isLoading}
    />
    
    <div class="flex space-x-3 pt-4">
      <Button 
        type="submit" 
        variant="primary"
        disabled={isLoading}
        loading={isLoading}
      >
        {isLoading ? 'Creating...' : 'Create Group'}
      </Button>
      
      <Button 
        type="button" 
        variant="secondary"
        on:click={onCancel}
        disabled={isLoading}
      >
        Cancel
      </Button>
    </div>
  </form>
</div>

<style>
  /* Additional custom styles if needed */
</style>

// frontend/src/designsystem/components/CreateGroupForm/CreateGroupForm.tsx
import { useState, useEffect } from 'react';
import Button from '../Button/Button';
import TextField from '../TextField/TextField';
import InlineToast from '../InlineToast/InlineToast';
import type { ToastVariant } from '../InlineToast/InlineToast';

export interface CreateGroupFormValues {
  name: string;
  identifier: string;
  description: string;
}

export interface CreateGroupFormProps {
  /**
   * Called on valid submission. Should return a promise that resolves on
   * success or rejects with an Error on failure.
   */
  onSubmit: (values: CreateGroupFormValues) => Promise<void>;
  /** Called when the user clicks Cancel. */
  onCancel?: () => void;
  /**
   * Pre-fill form fields. If `identifier` is set, the Group ID field is
   * locked (not auto-generated from name) and cannot be changed.
   */
  initialValues?: Partial<CreateGroupFormValues> | null;
}

interface FormErrors {
  name?: string;
  identifier?: string;
  description?: string;
}

interface ToastState {
  open: boolean;
  message: string;
  variant: ToastVariant;
}

function slugifyName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-+|-+$/g, '')
    .substring(0, 30);
}

/**
 * CreateGroupForm is a fully controlled form for creating (or editing) a group.
 *
 * - Auto-generates the Group ID slug from the name unless the user manually edits it.
 * - If `initialValues.identifier` is provided the Group ID field is locked.
 * - Manages async submission with an internal loading state.
 * - Displays success/error feedback via InlineToast anchored above the submit button.
 */
export default function CreateGroupForm({
  onSubmit,
  onCancel = () => {},
  initialValues = null,
}: CreateGroupFormProps) {
  const [name, setName] = useState(initialValues?.name ?? '');
  const [identifier, setIdentifier] = useState(initialValues?.identifier ?? '');
  const [description, setDescription] = useState(initialValues?.description ?? '');
  const [identifierManuallyEdited, setIdentifierManuallyEdited] = useState(
    !!initialValues?.identifier
  );
  const [errors, setErrors] = useState<FormErrors>({});
  const [loading, setLoading] = useState(false);
  const [toast, setToast] = useState<ToastState>({
    open: false,
    message: '',
    variant: 'success',
  });

  // Continuously sync identifier from name while not manually edited
  useEffect(() => {
    if (!identifierManuallyEdited) {
      setIdentifier(slugifyName(name));
    }
  }, [name, identifierManuallyEdited]);

  function validateForm(): boolean {
    const newErrors: FormErrors = {};

    if (!name.trim()) {
      newErrors.name = 'Group name is required';
    } else if (name.length < 3) {
      newErrors.name = 'Group name must be at least 3 characters';
    } else if (name.length > 50) {
      newErrors.name = 'Group name must be 50 characters or less';
    }

    if (!identifier.trim()) {
      newErrors.identifier = 'Group ID is required';
    } else if (!/^[a-zA-Z0-9-_]+$/.test(identifier)) {
      newErrors.identifier =
        'Group ID can only contain letters, numbers, hyphens, and underscores';
    } else if (identifier.length < 3) {
      newErrors.identifier = 'Group ID must be at least 3 characters';
    } else if (identifier.length > 30) {
      newErrors.identifier = 'Group ID must be 30 characters or less';
    }

    if (description && description.length > 200) {
      newErrors.description = 'Description must be 200 characters or less';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!validateForm()) return;

    setLoading(true);
    try {
      await onSubmit({ name, identifier, description });
      setToast({ open: true, message: 'Group created!', variant: 'success' });
    } catch (err) {
      setToast({
        open: true,
        message: err instanceof Error ? err.message : 'Failed to create group',
        variant: 'error',
      });
    } finally {
      setLoading(false);
    }
  }

  function handleIdentifierChange(value: string) {
    // If user diverges from auto slug, stop auto-updating
    const expected = slugifyName(name);
    if (value !== expected) {
      setIdentifierManuallyEdited(true);
    }
    setIdentifier(value);
  }

  return (
    <div className="bg-white border border-gray-200 rounded-lg p-6">
      <h2 className="text-xl font-semibold text-gray-900 mb-6">Create New Group</h2>

      <form onSubmit={handleSubmit} className="space-y-4">
        <TextField
          label="Group Name"
          value={name}
          onChange={setName}
          placeholder="Enter group name"
          validationMessage={errors.name}
          validationState={errors.name ? 'error' : 'none'}
          required
          disabled={loading}
        />

        <div>
          <TextField
            label="Group ID"
            value={identifier}
            onChange={handleIdentifierChange}
            placeholder="unique-group-id"
            validationMessage={errors.identifier}
            validationState={errors.identifier ? 'error' : 'none'}
            required
            disabled={loading || !!initialValues?.identifier}
          />
          <p className="mt-1 text-sm text-gray-500">
            {initialValues?.identifier
              ? 'Group ID cannot be changed after creation.'
              : 'This will be used to share your group with others. It must be unique.'}
          </p>
        </div>

        <TextField
          label="Description (Optional)"
          value={description}
          onChange={setDescription}
          placeholder="Describe your group..."
          validationMessage={errors.description}
          validationState={errors.description ? 'error' : 'none'}
          multiline
          disabled={loading}
        />

        <div className="flex space-x-3 pt-4">
          <div className="relative inline-toast-anchor">
            <Button type="submit" variant="primary" disabled={loading} loading={loading}>
              {loading ? 'Creating...' : 'Create Group'}
            </Button>
            <InlineToast
              open={toast.open}
              message={toast.message}
              variant={toast.variant}
              onClose={() => setToast((t) => ({ ...t, open: false }))}
            />
          </div>

          <Button type="button" variant="secondary" onClick={onCancel} disabled={loading}>
            Cancel
          </Button>
        </div>
      </form>
    </div>
  );
}
